# Generated by Django 3.0.8 on 2020-08-26 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='pdf',
            field=models.FileField(default='mozilla.pdf', upload_to=''),
        ),
    ]
