# Generated by Django 3.0.8 on 2020-08-28 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0003_auto_20200827_0326'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='preview',
            field=models.BooleanField(default=False),
        ),
    ]
