# Generated by Django 3.0.8 on 2020-08-28 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0004_lesson_preview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursestatus',
            name='completed_lessons',
        ),
        migrations.AlterField(
            model_name='lesson',
            name='preview',
            field=models.BooleanField(default=False, verbose_name='Show Preview'),
        ),
    ]
