# Generated by Django 3.0.8 on 2020-08-28 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0006_module_lessons_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='lessons_completed',
        ),
        migrations.AddField(
            model_name='coursestatus',
            name='completed_lessons',
            field=models.ManyToManyField(blank=True, related_name='completed_lessons', to='lms.Lesson'),
        ),
    ]
